### ISSUE TITLE
I found that "time" cannot be get

### ISSUE THREAD

**Issue by Jia35** [kevinzg/facebook-scraper#134]
I found that "time" cannot be get.
`... 'time': None ...`
It may be that the webpage has been modified.

What should i do?

**Comment by baraths92** [comment]
Hello. I do not know how to use time extraction engine. kindly help me

**Comment by geraldho** [comment]
Same error. I just get 'None' for 'time'.

**Comment by justpip** [comment]
Same issue for me. No 'time' data was extracted.

**Comment by GivenToFlyCoder** [comment]
Same issue! Can´t get date!

**Comment by kevinzg** [comment]
Should be fixed in v0.2.14, please reopen if date is still missing or wrong.

**Comment by justpip** [comment]
Thanks @kevinzg. It's working for me!

**Comment by Archelunch** [comment]
@kevinzg week ago everything works fine, but now time is also None, version is v0.2.14

**Comment by kevinzg** [comment]
@Archelunch we added some more cases, try again with version 0.2.15, if time is still missing, run it with `-vvv` if using the CLI, or call `facebook_scraper.enable_logging(logging.DEBUG)` before calling `get_posts`, that should print what dates it can't parse.

**Comment by prakhar-ai** [comment]
@kevinzg Time problem still doesn't seem to be fixed in v 0.2.15. Here is a part of my log:

`Extracting posts from page 1
Could not parse date: Yesterday at 15:28
Extract method extract_time didn't return anything
Extract method extract_link didn't return anything
Extract method extract_video didn't return anything
Extract method extract_video_thumbnail didn't return anything
Extract method extract_video_id didn't return anything
Could not parse date: Yesterday at 11:22
Extract method extract_time didn't return anything
Extract method extract_link didn't return anything
Could not parse date: Yesterday at 10:28
Extract method extract_time didn't return anything
Extract method extract_link didn't return anything
Extract method extract_video didn't return anything
Extract method extract_video_thumbnail didn't return anything
Extract method extract_video_id didn't return anything
Could not parse date: 7 November at 11:01
Extract method extract_time didn't return anything
Extract method extract_link didn't return anything
Looking for next page URL`

**Comment by Archelunch** [comment]
still doesn't work (
<img width="1012" alt="Снимок экрана 2020-11-10 в 14 21 45" src="https://user-images.githubusercontent.com/10900176/98667864-11f47c80-2360-11eb-9541-be6cba2b5654.png">

**Comment by kevinzg** [comment]
Try with 0.2.17.

**Comment by Archelunch** [comment]
> Try with 0.2.17.

Yeah, it works! Thank you
