### ISSUE TITLE
Can we add a feature to take the text of the comments of each post?

### ISSUE THREAD

**Issue by Hansyvea** [kevinzg/facebook-scraper#22]

**Comment by johantilli** [comment]
+1

**Comment by elyesmanai** [comment]
+1

**Comment by ManuelBanza** [comment]
@kevinzg any news about this development.
Congrats for the awesome work
Cheers!

**Comment by WajdiBenSaad** [comment]
I'm looking into this feature as well. any word about the person working on it? I don't see anyone assigned to this..

**Comment by Nellix** [comment]
Is anyone working on this feature? I can contribute too for this . Let me know.

**Comment by kevinzg** [comment]
@Nellix I don't think anyone is. If you could work on it that would be awesome.

**Comment by Nellix** [comment]
@kevinzg have you some pointers to understand the " Ectractor pattern " for the comment?  Thanks

**Comment by kevinzg** [comment]
@Nellix I'd probably start creating a method `extract_comments` in `PostExtractor` that returns a dict `{'comments': [...]}`, and add it to the method list in the `extract_post` method.
You can use `self.request` to do more network requests if needed.
If the code gets to complex you could create a `CommentsExtractor` class and put all the logic there.

**Comment by Nellix** [comment]
I have tried as you suggested... but I am not scraping nothing ... Can you be more precise? Thanks
How can I catch each comment for post? Should I retriebve the comment_id and then perform a new url in order to get the comment's text?

Thanks

**Comment by kevinzg** [comment]
I took a quick look at a FB post, it seems comments are not present on the mobile page, but they are on the `www.facebook.com` version.
You'd have to open the `www` version on the browser, inspect the HTML, observe what happens when you click on `X Comments` and on `View more comments` (they should fire events that do API requests to FB and their responses should contain the comments).
Identify those requests and see what parameters are being sent and where they come from.
Once you got that try to simulate them with Python.

**Comment by Nellix** [comment]
Can I have your email Kevin? I need to talk with you about business.
Thanks,
Aniello

**Comment by kevinzg** [comment]
@Nellix you can get my email from the [project page][1] at PyPI.

[1]: https://pypi.org/project/facebook-scraper/

**Comment by mellanon** [comment]
@Nellix how did you go with adding this feature?

**Comment by andcha** [comment]
Getting post comment would be a killer feature.. Hoping something works out soon..
