### ISSUE TITLE
Scraping from docker container

### ISSUE THREAD

**Issue by panichmaxim** [kevinzg/facebook-scraper#294]
Does anyone have troubles using library from docker container?
I launched working code from host system via `python app.py` and via docker-compose and code from docker container didnt work:

`def parse():`
    `accounts = ["zuck"]  #`
    `facebook_scraper.enable_logging()`
    `for name in accounts:`
        `posts = facebook_scraper.get_posts(account=name, credentials=credentials)`
       ` i = 0`
        `for post in posts:`
            `if i == 3:`
                `break`
            `print(post['post_text'])`
            `print(post['post_url'])`
            `print(post['time'])`
            `print(post['post_id'])`
            
What could be the issue? Maybe I should open specific ports? 
Also the strange thing is that from docker container I am able to parse posts from my account (i.e. credentials), but could not parse others.
I am a little bit confused and dont know where to dig

**Comment by neon-ninja** [comment]
Can you provide the exact docker command you used? I tested with `docker run -it python:3.7-buster bash -c 'pip install facebook-scraper; python -c "import facebook_scraper; print(next(facebook_scraper.get_posts(\"Nintendo\")))"'` and it worked fine

**Comment by panichmaxim** [comment]
@neon-ninjia
Created a simple demo:
https://github.com/panichmaxim/scrapper
Commands to start:
1. First case
`docker-compose build`
`docker-compose up`

error for zuck page, but no errors for my page (also my page is credentials) ->
facebook_parser_1  | No raw posts (<article> elements) were found in this page.
facebook_parser_1  | Page parser did not find next page URL
2. Second case
python facebook_parser.py

No errors for zuck account

**Comment by neon-ninja** [comment]
I think this problem is unrelated to docker, it's actually a version issue. This commit changed the login flow a bit (https://github.com/kevinzg/facebook-scraper/commit/18d9d539cb8fc95ac527027f81289071a0423b31). This commit refactors submitting a form into a function, for which the 2FA part of the login flow required the selector "input[name][value]", whereas the old selector was '#login_form > input[name][value]'. In doing so, it inadvertently sends _fb_noscript=True on login. Subsequent to that successful login, Facebook serves JS-free/mbasic content on the m.facebook.com domain, which the scraper doesn't expect, and post extraction fails.

So, if you had v0.2.37 installed locally, but v0.2.38 in Docker, login would work locally but not in Docker.

This commit (https://github.com/kevinzg/facebook-scraper/commit/87b15a520a18c5a064ea6a983690e2c2582f8e5a) should fix the problem.

**Comment by panichmaxim** [comment]
Thx!
