### ISSUE TITLE
About the pages parameter

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#383]
I would need to clarify the meaning of the pages parameter.  It states it is the pages of post to request.  What is a page of post actually? Is it independent on the no. of comments? Say, for some page, a page of 10 can return 300 comments while for other page, a page of 10 can return 2000 comments? 
So, does it mean that I need to set the pages parameter differently for different pages to avoid getting banned? I would like to deduce a rule of thumb, i.e. set the pages parameter such as the no. of comments returned is around 3000, etc.

**Comment by neon-ninja** [comment]
When you scroll down on a Page or a Group on Facebook, it loads posts in pages. This varies depending on whether you're scraping Pages or Groups - for Pages, you get 2 posts on the first request, then 4 posts per page for each subsequent request (unless you change that default with the posts_per_page parameter). Groups give you roughly 20 posts per page, but this can vary by +-10 posts. The number of posts per page for a group cannot be changed. The pages parameter limits how many pages to retrieve. Extracting comments from posts is a separate process, so yes, the page limit is independent from the number of comments. The number of comments would vary from Page to Page, as some Pages are more popular than others, and tend to have more comments per post.

As `get_posts` returns a generator, you can consume just enough posts until you have your comment limit, then terminate iteration. You can set pages to None, so that you'll continue retrieving posts until you hit your comment limit. Here's is a code example:

```python
comments = 0
for post in get_posts("Nintendo", cookies="cookies.txt", pages=None, options={"comments": 3000}):
    comments += len(post["comments_full"])
    if comments > 3000:
        break
```

Note that I also set the limit of comments on a given post to 3000 - so if the first post you get has > 3000 comments (possible for Pages belonging to movie stars), you'll only get comments for that one post

**Comment by cmhcheung** [comment]
So the IP ban is related to no. of comments instead of no. of posts, right?  It may seem more straightforward to specify the limit on no. of comments instead (Say, 5000 comments per hour) as there is no need to adjust the parameter for difficult pages.  I will try to code.

**Comment by neon-ninja** [comment]
I don't think so - I think it's related to number of requests made in a given time window. Some request types seem easier to trigger a temporary ban than others (50 get_profile requests in rapid succession triggers a temporary ban, similar for getting a users friends), but it is still technically possible to trigger a temporary ban scraping posts alone, without comments.
